services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/pgsql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=go_judge_db
      - POSTGRES_PASSWORD=admin