services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/pgsql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=go_judge_db
      - POSTGRES_PASSWORD=admin
  rabbitmq:
    image: rabbitmq:4-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "15672:15672"
      - "5672:5672"